-- GENERATED by scripts/trig_approx_parameters/gen_vhdl_pkg.py
--
-- Coefficient ROMs for the GIVENSQ hardware unit, from the same CSD
-- table as src/common/trig_pwl_csd.h and src/common/givensq_fw.S.
-- The C model, the ARM assembly and this VHDL are therefore
-- bit-identical by construction, and one set of test vectors
-- validates all three.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package givensq_pkg is
  constant TRIG_Q      : integer := 14;
  constant SEG_BITS    : integer := 4;
  constant INDEX_SHIFT : integer := 10;
  constant PI_2_FIXED  : integer := 25736;  -- pi/2 in Q14
  constant PI_4_FIXED  : integer := 12868;  -- pi/4 in Q14, fold threshold

  type coeff_t is record
    m : integer;
    b : integer;
  end record;
  type coeff_array is array (natural range <>) of coeff_t;

  constant ROM_ARCTAN : coeff_array(0 to 16) := (
    (m =>  16364, b =>      1),
    (m =>  16240, b =>      9),
    (m =>  16000, b =>     39),
    (m =>  15616, b =>    111),
    (m =>  15232, b =>    206),
    (m =>  14592, b =>    406),
    (m =>  14080, b =>    600),
    (m =>  13312, b =>    938),
    (m =>  12800, b =>   1198),
    (m =>  12160, b =>   1556),
    (m =>  11264, b =>   2119),
    (m =>  10752, b =>   2480),
    (m =>  10176, b =>   2914),
    (m =>   9472, b =>   3488),
    (m =>   8960, b =>   3941),
    (m =>   8452, b =>   4419),
    (m =>   8452, b =>   4419)
  );

  constant ROM_SIN : coeff_array(0 to 13) := (
    (m =>  16374, b =>      1),
    (m =>  16312, b =>      5),
    (m =>  16192, b =>     19),
    (m =>  16000, b =>     55),
    (m =>  15744, b =>    119),
    (m =>  15424, b =>    219),
    (m =>  15104, b =>    337),
    (m =>  14592, b =>    560),
    (m =>  14080, b =>    818),
    (m =>  13824, b =>    955),
    (m =>  12800, b =>   1593),
    (m =>  12320, b =>   1931),
    (m =>  11776, b =>   2338),
    (m =>  11776, b =>   2338)
  );

  constant ROM_COS : coeff_array(0 to 13) := (
    (m =>   -512, b =>  16388),
    (m =>  -1534, b =>  16452),
    (m =>  -2552, b =>  16580),
    (m =>  -3552, b =>  16767),
    (m =>  -4544, b =>  17015),
    (m =>  -5632, b =>  17357),
    (m =>  -6400, b =>  17646),
    (m =>  -7424, b =>  18093),
    (m =>  -8304, b =>  18534),
    (m =>  -9152, b =>  19011),
    (m =>  -9984, b =>  19530),
    (m => -10752, b =>  20056),
    (m => -11264, b =>  20435),
    (m => -11264, b =>  20435)
  );

end package givensq_pkg;
