#!/usr/bin/env python3
"""Generate hw/givensq_pkg.vhd -- the coefficient ROMs for the VHDL unit.

Emitted from the SAME CSD table as src/common/trig_pwl_csd.h and
src/common/givensq_fw.S, so the C model, the ARM assembly and the hardware are
bit-identical by construction rather than by inspection. That is what lets one
set of test vectors validate all three.

Usage: gen_vhdl_pkg.py > ../../hw/givensq_pkg.vhd
"""

import importlib.util
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location(
    "g", os.path.join(HERE, "gen_pwl_tables.py"))
g = importlib.util.module_from_spec(spec)
spec.loader.exec_module(g)

Q, P = 14, 4
SC = 1 << Q
PI4 = np.pi / 4


def build(f, lo, hi):
    """Shared builder -- see gen_pwl_tables.build_csd_table for why this must
    NOT be a local re-implementation."""
    return [(m, b) for m, b, _ in g.build_csd_table(f, lo, hi, P)]


def main():
    tables = (("ARCTAN", build(np.arctan, 0.0, 1.0)),
              ("SIN", build(np.sin, 0.0, PI4)),
              ("COS", build(np.cos, 0.0, PI4)))

    print("-- GENERATED by scripts/trig_approx_parameters/gen_vhdl_pkg.py")
    print("--")
    print("-- Coefficient ROMs for the GIVENSQ hardware unit, from the same CSD")
    print("-- table as src/common/trig_pwl_csd.h and src/common/givensq_fw.S.")
    print("-- The C model, the ARM assembly and this VHDL are therefore")
    print("-- bit-identical by construction, and one set of test vectors")
    print("-- validates all three.")
    print("library ieee;")
    print("use ieee.std_logic_1164.all;")
    print("use ieee.numeric_std.all;")
    print()
    print("package givensq_pkg is")
    print(f"  constant TRIG_Q      : integer := {Q};")
    print(f"  constant SEG_BITS    : integer := {P};")
    print(f"  constant INDEX_SHIFT : integer := {Q - P};")
    print("  constant PI_2_FIXED  : integer := 25736;  -- pi/2 in Q14")
    print("  constant PI_4_FIXED  : integer := 12868;  -- pi/4 in Q14, fold threshold")
    print()
    print("  type coeff_t is record")
    print("    m : integer;")
    print("    b : integer;")
    print("  end record;")
    print("  type coeff_array is array (natural range <>) of coeff_t;")
    print()
    for name, t in tables:
        print(f"  constant ROM_{name} : coeff_array(0 to {len(t) - 1}) := (")
        print(",\n".join(f"    (m => {m:6d}, b => {b:6d})" for m, b in t))
        print("  );")
        print()
    print("end package givensq_pkg;")


if __name__ == "__main__":
    main()
