#!/usr/bin/env python3
"""Generate src/common/trig_pwl_csd.h -- the firmware (multiplier-free) tables.

Uses the shared builder in gen_pwl_tables.build_csd_table, as do the VHDL
package and the ARM assembly. See that function for what went wrong when each
emitter had its own copy.

Usage: gen_csd_header.py > ../../src/common/trig_pwl_csd.h
"""
import importlib.util, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("g", os.path.join(HERE, "gen_pwl_tables.py"))
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
Q, P = g.TRIG_Q, 4
PI4 = np.pi / 4

print("/* GENERATED by scripts/trig_approx_parameters/gen_csd_header.py -- do not edit.")
print(" *")
print(" * Firmware PWL tables. Slopes are constrained to three signed powers of two")
print(" * so the microcoded engine, which has no multiplier, evaluates m*x as three")
print(" * shift-adds. The constrained slope is still an exact integer, so (m*x)>>14")
print(" * here is bit-identical to the assembly's shift-add chain and to the VHDL.")
print(" *")
print(" * SEPARATE from trig_pwl_tables.h on purpose: the real ARM has SMULL, so the")
print(" * software variants keep exact slopes and their better accuracy. Only the")
print(" * firmware and the hardware are multiplier-free. */")
print("#ifndef TRIG_PWL_CSD_H\n#define TRIG_PWL_CSD_H\n\n#include <stdint.h>\n")
print(f"#define CSD_SEG_BITS {P}\n#define CSD_TRIG_Q   {Q}")
print("#define CSD_INDEX_SHIFT (CSD_TRIG_Q - CSD_SEG_BITS)\n")
for name, f, lo, hi in (("arctan", np.arctan, 0.0, 1.0),
                        ("sin", np.sin, 0.0, PI4), ("cos", np.cos, 0.0, PI4)):
    ents = g.build_csd_table(f, lo, hi, P)
    U = name.upper()
    print(f"#define CSD_{U}_SEGS {len(ents)}")
    print(f"static const int32_t csd_{name}[CSD_{U}_SEGS] = {{")
    for i, (m, c, t) in enumerate(ents):
        e = " ".join(f"{'+' if s > 0 else '-'}2^{a}" for s, a in t)
        print(f"    0x{(((c & 0xFFFF) << 16) | (m & 0xFFFF)):08X}, "
              f"/* [{i:2d}] m={m:6d} = {e:<22s} b={c:6d} */")
    print("};\n")
print("#endif /* TRIG_PWL_CSD_H */")
