#!/usr/bin/env python3
"""Emit docs/PWL_ERROR.md -- the approximation-error deliverable.

Lesson 112, project requirements I:
    "Consider the piecewise linear approximation for arctan, sin, and cos,
     and determine the maximum error for three middle points"

"Middle points" are read as the interior error extrema: on each segment the
approximation touches the function near the ends and deviates most somewhere
inside, so the interesting error is at those interior points, not at the
breakpoints. They are located exactly (f'(x) = slope) rather than sampled.

Two approximations are reported:
  - the notes' own reference for arctan (0.928x, 0.644x +/- 0.142), which is
    the baseline the requirement is stated against;
  - the tables this project actually ships, from gen_pwl_tables.py.

Usage: pwl_error_table.py > ../../docs/PWL_ERROR.md
"""

import os
import re
import numpy as np

Q = 14
SCALE = 1 << Q
PI4 = np.pi / 4
HERE = os.path.dirname(os.path.abspath(__file__))
TABLES = os.path.join(HERE, "..", "..", "src", "common", "trig_pwl_tables.h")


# --- the notes' reference arctan -------------------------------------------
def notes_arctan(x):
    return np.where(np.abs(x) <= 0.5, 0.928 * x,
                    np.where(x > 0, 0.644 * x + 0.142, 0.644 * x - 0.142))


def interior_extremum(fprime_inv, slope, lo, hi):
    """x in (lo, hi) where f'(x) == slope, or None if the slope is unreachable."""
    x = fprime_inv(slope)
    return x if x is not None and lo < x < hi else None


def report_segment(f, approx, lo, hi, n=200001):
    x = np.linspace(lo, hi, n)
    e = approx(x) - f(x)
    i = int(np.argmax(np.abs(e)))
    return x[i], e[i]


# --- the shipped tables -----------------------------------------------------
def load_tables():
    src = open(TABLES).read()
    segbits = int(re.search(r"#define PWL_SEG_BITS (\d+)", src).group(1))
    out = {}
    for name in ("arctan", "sin", "cos"):
        body = re.search(rf"pwl_{name}\[[^\]]*\] = \{{(.*?)\}};", src, re.S).group(1)
        ent = []
        for m, b in re.findall(r"m=\s*(-?\d+) b=\s*(-?\d+)", body):
            ent.append((int(m), int(b)))
        out[name] = ent
    return segbits, out


def table_eval(entries, segbits, x):
    """Bit-exact replica of pwl_eval() in src/common/trig_pwl.c."""
    xq = np.round(np.abs(x) * SCALE).astype(np.int64)
    idx = np.minimum(xq >> (Q - segbits), len(entries) - 1)
    m = np.array([e[0] for e in entries], dtype=np.int64)[idx]
    b = np.array([e[1] for e in entries], dtype=np.int64)[idx]
    return (((m * xq) >> Q) + b) / SCALE


def main():
    segbits, tabs = load_tables()
    w = 2.0 ** -segbits

    print("# Piecewise-Linear Approximation Error\n")
    print("Deliverable for Lesson 112, project requirements I: *\"determine the")
    print("maximum error for three middle points\"*.\n")
    print("Generated by `scripts/trig_approx_parameters/pwl_error_table.py`.")
    print("\"Middle points\" are the interior error extrema -- the approximation")
    print("meets the curve near each breakpoint and deviates most inside the")
    print("segment, so those interior points are where the error lives. They are")
    print("solved for exactly (f'(x) = segment slope), not sampled.\n")

    # ---- the notes' reference ---------------------------------------------
    print("## 1. The notes' reference approximation (arctan)\n")
    print("```")
    print("arctan(x) ~=  0.928x            |x| <= 0.5")
    print("              0.644x + 0.142     0.5 < x <= 1.0")
    print("              0.644x - 0.142    -1.0 <= x < -0.5")
    print("```\n")
    print("In Q11 integer form, as the notes give it: 1900, 1319, 291, "
          "breakpoint 1024.\n")
    print("| segment | slope | middle point | error there | max \\|error\\| |")
    print("|---|---:|---:|---:|---:|")
    segs = [("[0, 0.5]", 0.928, 0.0, 0.5), ("[0.5, 1.0]", 0.644, 0.5, 1.0)]
    notes_worst = 0.0
    for label, slope, lo, hi in segs:
        # arctan'(x) = 1/(1+x^2) = slope  ->  x = sqrt(1/slope - 1)
        xm = np.sqrt(1.0 / slope - 1.0) if slope < 1 else None
        xm = xm if xm is not None and lo < xm < hi else None
        xw, ew = report_segment(np.arctan, notes_arctan, lo, hi)
        notes_worst = max(notes_worst, abs(ew))
        em = float(notes_arctan(np.array([xm]))[0] - np.arctan(xm)) if xm else float("nan")
        xs = f"{xm:.4f}" if xm else "--"
        es = f"{em:+.5f}" if xm else "--"
        print(f"| {label} | {slope} | {xs} | {es} | {abs(ew):.5f} |")
    xm3 = -np.sqrt(1.0 / 0.644 - 1.0)
    em3 = float(notes_arctan(np.array([xm3]))[0] - np.arctan(xm3))
    print(f"\nThe third middle point is the mirror of the second, at "
          f"x = {xm3:.4f}, error {em3:+.5f} (arctan is odd).\n")
    print(f"**Maximum error of the notes' arctan: {notes_worst:.5f}** "
          f"({notes_worst*100:.2f} % of full scale).\n")

    # ---- shipped tables ----------------------------------------------------
    print(f"## 2. This project's tables (P = {segbits}, segment width 2^-{segbits})\n")
    print("Uniform segment width, so the segment index is a shift and the cost")
    print("does not grow with the number of segments.\n")
    for name, f, lo, hi in (("arctan", np.arctan, 0.0, 1.0),
                            ("sin", np.sin, 0.0, PI4),
                            ("cos", np.cos, 0.0, PI4)):
        ent = tabs[name]
        nseg = int(np.ceil((hi - lo) / w))
        print(f"### {name}  ({nseg} segments over [{lo:.4f}, {hi:.4f}])\n")
        print("| segment | middle point | error there |")
        print("|---|---:|---:|")
        worst = 0.0
        rows = []
        for i in range(nseg):
            a, b = lo + i * w, min(lo + (i + 1) * w, hi)
            xx = np.linspace(a, b, 20001)
            ee = table_eval(ent, segbits, xx) - f(xx)
            j = int(np.argmax(np.abs(ee)))
            worst = max(worst, abs(ee[j]))
            rows.append((a, b, xx[j], ee[j]))
        # three middle points: the three worst segments
        for a, b, xm, em in sorted(rows, key=lambda r: -abs(r[3]))[:3]:
            print(f"| [{a:.4f}, {b:.4f}] | {xm:.4f} | {em:+.6f} |")
        print(f"\nMaximum error: **{worst:.6f}**\n")

    print("## 3. Comparison\n")
    print("| approximation | max error | vs notes' reference |")
    print("|---|---:|---:|")
    print(f"| notes' arctan (2 segments, Q11) | {notes_worst:.5f} | 1.00x |")
    for name, f, lo, hi in (("arctan", np.arctan, 0.0, 1.0),
                            ("sin", np.sin, 0.0, PI4),
                            ("cos", np.cos, 0.0, PI4)):
        xx = np.linspace(lo, hi, 200001)
        e = float(np.max(np.abs(table_eval(tabs[name], segbits, xx) - f(xx))))
        print(f"| this project, {name} (P={segbits}, Q{Q}) | {e:.6f} | "
              f"{notes_worst/e:.1f}x better |")
    print()
    print("The notes' constants are round numbers chosen to be readable, not")
    print("minimax-optimal: a proper 2-segment fit on the same breakpoint already")
    print("halves the error at identical cost. The remaining gain is segment count,")
    print("which is free here because the index is a shift.\n")
    print("Error enters the QR result through the rotation coefficients, so it is")
    print("the *orthogonality* of Q that ultimately matters -- see the accuracy")
    print("suite, which measures |I - QQ^T| directly.")


if __name__ == "__main__":
    main()
