#!/usr/bin/env python3
"""Generate src/common/givensq_fw.S -- GIVENSQ in ARM assembly, no MUL, no SDIV.

Scenario step 5 ("optimise by hand the assembly code, assemble it and run it on
an ARM machine") and the implementation half of step 7. `givensq_fw.c` is the
specification; this must agree with it bit-for-bit on every input.

Generated rather than hand-typed for one reason: the per-segment coefficients
come from the SAME CSD table as the C model, so the two cannot drift apart. A
hand-written copy of 45 segments would be a transcription error waiting to
happen.

Two structural choices worth knowing when reading the output:

  * The divide is UNROLLED, 14 iterations of exactly four instructions
    (lsl / cmp / subhs / adc). A microprogram has no loop overhead, so
    unrolling is what makes the assembly comparable to the hand-counted
    microcode instead of ~40% longer.

  * Each PWL segment is its own code block reached through a jump table, which
    is the ARM equivalent of a microcoded engine branching into a per-segment
    micro-routine with the coefficients as control-store literals.

Usage: gen_givensq_asm.py > src/common/givensq_fw.S
"""

import importlib.util
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location(
    "g", os.path.join(HERE, "gen_pwl_tables.py"))
g = importlib.util.module_from_spec(spec)
spec.loader.exec_module(g)

Q = 14
SC = 1 << Q
P = 4
PI4 = np.pi / 4
PI_2_FIXED = 25736
PI_4_FIXED = 12868

out = []
def w(line=""):
    out.append(line)


def build(f, lo, hi):
    """Shared builder -- see gen_pwl_tables.build_csd_table for why this must
    NOT be a local re-implementation."""
    return g.build_csd_table(f, lo, hi, P)


def emit_const(reg, value):
    """Materialise a 32-bit constant. movw/movt, so no literal pool and no load."""
    v = value & 0xFFFFFFFF
    w(f"    movw    {reg}, #{v & 0xFFFF}")
    if (v >> 16) & 0xFFFF:
        w(f"    movt    {reg}, #{(v >> 16) & 0xFFFF}")


def emit_pwl(name, ents):
    """PWL evaluator: r2 = |x| in, r3 = result out. Clobbers r3, r6, r12."""
    tag = name[:2]
    w(f"@ ---- {name}: {len(ents)} segments, dispatch on |x| >> {Q - P} --------")
    w(f".Lpwl_{name}:")
    w(f"    lsr     r12, r2, #{Q - P}          @ segment index: one shift")
    w(f"    adr     r6, .L{tag}_table")
    w(f"    ldr     pc, [r6, r12, lsl #2]   @ branch into the segment's routine")
    w(f".L{tag}_table:")
    for i in range(len(ents)):
        w(f"    .word   .L{tag}_s{i}")
    for i, (m, b, terms) in enumerate(ents):
        expr = " ".join(f"{'+' if s > 0 else '-'}2^{a}" for s, a in terms)
        w(f".L{tag}_s{i}:                       @ m={m} = {expr}, b={b}")
        # m*x as three shift-adds, accumulated at full width then shifted once,
        # which is bit-identical to (m*x)>>14 with the integer m.
        first = True
        for sgn, sh in terms:
            if first:
                if sgn > 0:
                    w(f"    lsl     r3, r2, #{sh}")
                else:
                    w(f"    lsl     r3, r2, #{sh}")
                    w(f"    rsb     r3, r3, #0")
                first = False
            else:
                op = "add" if sgn > 0 else "sub"
                w(f"    {op}     r3, r3, r2, lsl #{sh}")
        w(f"    asr     r3, r3, #{Q}")
        if b:
            emit_const("r6", b)
            w("    add     r3, r3, r6")
        w(f"    b       .Lpwl_{name}_done")
    w(f".Lpwl_{name}_done:")
    w("    bx      lr")
    w()


def main():
    at = build(np.arctan, 0.0, 1.0)
    sn = build(np.sin, 0.0, PI4)
    cs = build(np.cos, 0.0, PI4)

    w("@ GENERATED by scripts/gen_givensq_asm.py -- do not edit.")
    w("@")
    w("@ GIVENSQ for the microcoded engine: no MUL, no MLA, no SDIV, no UDIV.")
    w("@ Specification is src/common/givensq_fw.c; the two must agree bit-for-bit")
    w("@ on every input, which tests/test_givensq_fw.c checks.")
    w("@")
    w("@   int32_t givensq_fw_asm(int32_t opposite, int32_t adjacent)")
    w("@   r0 = opposite, r1 = adjacent -> r0 = (sin:cos), Q14 halves")
    w()
    w("    .syntax unified")
    w("    .arch   armv7-a")
    w("    .text")
    w("    .align  2")
    w("    .global givensq_fw_asm")
    w("    .type   givensq_fw_asm, %function")
    w()
    w("givensq_fw_asm:")
    w("    push    {r4-r8, r10, lr}")
    w()
    w("    @ ---- operand prep: |o|, |a|, sign, swap decision ----------------")
    w("    eor     r8, r0, r1              @ r8<31> = sign of the ratio")
    w("    cmp     r1, #0")
    w("    bne     .Lnormal")
    w()
    w("    @ adjacent == 0: angle = +/- pi/2, no divide")
    emit_const("r7", PI_2_FIXED)
    w("    cmp     r0, #0")
    w("    rsblt   r7, r7, #0")
    w("    b       .Lhave_angle")
    w()
    w(".Lnormal:")
    w("    cmp     r0, #0")
    w("    rsblt   r2, r0, #0              @ r2 = |opposite|")
    w("    movge   r2, r0")
    w("    cmp     r1, #0")
    w("    rsblt   r3, r1, #0              @ r3 = |adjacent|")
    w("    movge   r3, r1")
    w()
    w("    cmp     r2, r3                  @ swapped = |o| > |a|")
    w("    movhi   r10, #1")
    w("    movls   r10, #0")
    w("    movhi   r4, r3                  @ n = min(|o|,|a|)")
    w("    movhi   r5, r2                  @ d = max(|o|,|a|)")
    w("    movls   r4, r2")
    w("    movls   r5, r3")
    w()
    w("    @ ---- restoring divide: ratio = (n << 14) / d, Q14 ---------------")
    w("    @ n == d needs a 15-bit quotient (exactly 1.0), which a 14-iteration")
    w("    @ binary loop cannot produce -- handled as a special case, matching")
    w("    @ fw_divide_restoring() in the C model.")
    w("    cmp     r4, r5")
    w("    bhs     .Lratio_one")
    w("    mov     r6, r4                  @ rem = n")
    w("    mov     r7, #0                  @ quo = 0")
    w("    @ 14 iterations, unrolled: a microprogram has no loop overhead, so")
    w("    @ unrolling is what makes this comparable to the hand cycle count.")
    for i in range(Q):
        w(f"    lsl     r6, r6, #1              @ [{i:2d}] rem <<= 1")
        w("    cmp     r6, r5")
        w("    subhs   r6, r6, r5")
        w("    adc     r7, r7, r7              @ quo = quo<<1 | carry")
    w("    b       .Lhave_ratio")
    w(".Lratio_one:")
    emit_const("r7", 1 << Q)
    w(".Lhave_ratio:")
    w("    cmp     r8, #0")
    w("    rsblt   r7, r7, #0              @ apply the ratio's sign")
    w()
    w("    @ ---- angle = arctan(ratio) --------------------------------------")
    w("    cmp     r7, #0")
    w("    rsblt   r2, r7, #0")
    w("    movge   r2, r7")
    w("    bl      .Lpwl_arctan")
    w("    cmp     r7, #0")
    w("    rsblt   r3, r3, #0              @ arctan is odd")
    w("    mov     r7, r3")
    w()
    w("    @ ---- quadrant fix-up: if swapped, angle = +/- pi/2 - angle ------")
    w("    cmp     r10, #0")
    w("    beq     .Lhave_angle")
    emit_const("r6", PI_2_FIXED)
    w("    cmp     r8, #0")
    w("    rsblt   r6, r6, #0")
    w("    sub     r7, r6, r7")
    w()
    w(".Lhave_angle:")
    w("    @ ---- c = cos(angle), s = sin(angle) -----------------------------")
    w("    mov     r0, r7                  @ both entries take the angle in r0;")
    w("    bl      .Lcos_entry             @ neither clobbers r7, so it survives")
    w("    mov     r4, r3                  @ r4 = c")
    w("    mov     r0, r7")
    w("    bl      .Lsin_entry")
    w("    mov     r5, r3                  @ r5 = s")
    w()
    w("    @ ---- pack: s in the high half, c in the low half ----------------")
    w("    uxth    r0, r4")
    w("    orr     r0, r0, r5, lsl #16")
    w("    pop     {r4-r8, r10, pc}")
    w()
    w("@ ---- sin/cos with the |x| > pi/4 fold ------------------------------")
    w("@ r0 = angle in, r3 = result out. The fold makes these mutually")
    w("@ recursive in C; here each calls the OTHER's table directly, so the")
    w("@ recursion is one level deep by construction and needs no stack.")
    w(".Lcos_entry:")
    w("    push    {r4, lr}")
    w("    cmp     r0, #0")
    w("    rsblt   r2, r0, #0")
    w("    movge   r2, r0                  @ r2 = |angle|, cos is even")
    emit_const("r6", PI_4_FIXED)
    w("    cmp     r2, r6")
    w("    bls     .Lcos_direct")
    emit_const("r6", PI_2_FIXED)
    w("    sub     r2, r6, r2              @ fold: cos(x) = sin(pi/2 - x)")
    w("    mov     r4, r2                  @ pi/2 - |x| GOES NEGATIVE for")
    w("    cmp     r2, #0                  @ |x| > pi/2, and sine is ODD --")
    w("    rsblt   r2, r2, #0              @ so the sign must be carried")
    w("    bl      .Lpwl_sin               @ across the fold, not discarded")
    w("    cmp     r4, #0")
    w("    rsblt   r3, r3, #0")
    w("    pop     {r4, pc}")
    w(".Lcos_direct:")
    w("    bl      .Lpwl_cos")
    w("    pop     {r4, pc}")
    w()
    w(".Lsin_entry:")
    w("    push    {lr}")
    w("    cmp     r0, #0")
    w("    rsblt   r2, r0, #0")
    w("    movge   r2, r0                  @ r2 = |angle|")
    emit_const("r6", PI_4_FIXED)
    w("    cmp     r2, r6")
    w("    bls     .Lsin_direct")
    emit_const("r6", PI_2_FIXED)
    w("    sub     r2, r6, r2              @ fold: sin(x) = cos(pi/2 - x)")
    w("    cmp     r2, #0")
    w("    rsblt   r2, r2, #0              @ cos is EVEN, so abs is safe here")
    w("    bl      .Lpwl_cos")
    w("    b       .Lsin_sign")
    w(".Lsin_direct:")
    w("    bl      .Lpwl_sin")
    w(".Lsin_sign:")
    w("    cmp     r0, #0")
    w("    rsblt   r3, r3, #0              @ sine is odd")
    w("    pop     {pc}")
    w()
    emit_pwl("arctan", at)
    emit_pwl("sin", sn)
    emit_pwl("cos", cs)
    w("    .size   givensq_fw_asm, .-givensq_fw_asm")
    w("    .section .note.GNU-stack,\"\",%progbits")

    print("\n".join(out))
    ins = sum(1 for l in out
              if l.startswith("    ") and not l.lstrip().startswith(("@", ".")))
    print(f"@ instructions emitted: {ins}", file=sys.stderr)


if __name__ == "__main__":
    main()
