/* GENERATED by scripts/trig_approx_parameters/gen_pwl_tables.py 4 -- do not edit. */
#ifndef TRIG_PWL_TABLES_H
#define TRIG_PWL_TABLES_H

#include <stdint.h>

#define PWL_SEG_BITS 4
#define PWL_TRIG_Q   14

/* Segment index = |x| >> PWL_INDEX_SHIFT: one LSR, constant in the
   number of segments. Coefficients are packed b:m, one load. */
#define PWL_INDEX_SHIFT (PWL_TRIG_Q - PWL_SEG_BITS)

/* arctan: 16 segments of width 2^-4 over [0.0000, 1.0000], max error 0.000272 (coefficients quantised) */
#define PWL_ARCTAN_SEGS 16
static const int32_t pwl_arctan[PWL_ARCTAN_SEGS] = {
    0x00003FEB, /* [0] m= 16363 b=     0 */
    0x00093F6C, /* [1] m= 16236 b=     9 */
    0x00283E75, /* [2] m= 15989 b=    40 */
    0x006B3D10, /* [3] m= 15632 b=   107 */
    0x00DD3B4C, /* [4] m= 15180 b=   221 */
    0x0182393A, /* [5] m= 14650 b=   386 */
    0x025F36ED, /* [6] m= 14061 b=   607 */
    0x03733478, /* [7] m= 13432 b=   883 */
    0x04BA31E9, /* [8] m= 12777 b=  1210 */
    0x06302F52, /* [9] m= 12114 b=  1584 */
    0x07CD2CBD, /* [10] m= 11453 b=  1997 */
    0x098B2A34, /* [11] m= 10804 b=  2443 */
    0x0B6227BF, /* [12] m= 10175 b=  2914 */
    0x0D4C2564, /* [13] m=  9572 b=  3404 */
    0x0F432325, /* [14] m=  8997 b=  3907 */
    0x11412105, /* [15] m=  8453 b=  4417 */
};

/* sin: 13 segments of width 2^-4 over [0.0000, 0.7854], max error 0.000236 (coefficients quantised) */
#define PWL_SIN_SEGS 13
static const int32_t pwl_sin[PWL_SIN_SEGS] = {
    0x00003FF5, /* [0] m= 16373 b=     0 */
    0x00043FB5, /* [1] m= 16309 b=     4 */
    0x00153F36, /* [2] m= 16182 b=    21 */
    0x00393E77, /* [3] m= 15991 b=    57 */
    0x00783D7A, /* [4] m= 15738 b=   120 */
    0x00DB3C3F, /* [5] m= 15423 b=   219 */
    0x01683AC8, /* [6] m= 15048 b=   360 */
    0x02263916, /* [7] m= 14614 b=   550 */
    0x031B372C, /* [8] m= 14124 b=   795 */
    0x044E350A, /* [9] m= 13578 b=  1102 */
    0x05C532B3, /* [10] m= 12979 b=  1477 */
    0x07843029, /* [11] m= 12329 b=  1924 */
    0x09182E0C, /* [12] m= 11788 b=  2328 */
};

/* cos: 13 segments of width 2^-4 over [0.0000, 0.7854], max error 0.000325 (coefficients quantised) */
#define PWL_COS_SEGS 13
static const int32_t pwl_cos[PWL_COS_SEGS] = {
    0x4004FE00, /* [0] m=  -512 b= 16388 */
    0x4044FA02, /* [1] m= -1534 b= 16452 */
    0x40C3F60B, /* [2] m= -2549 b= 16579 */
    0x417FF21D, /* [3] m= -3555 b= 16767 */
    0x4277EE3D, /* [4] m= -4547 b= 17015 */
    0x43A8EA6F, /* [5] m= -5521 b= 17320 */
    0x450DE6B7, /* [6] m= -6473 b= 17677 */
    0x46A2E317, /* [7] m= -7401 b= 18082 */
    0x4863DF95, /* [8] m= -8299 b= 18531 */
    0x4A4ADC33, /* [9] m= -9165 b= 19018 */
    0x4C51D8F5, /* [10] m= -9995 b= 19537 */
    0x4E71D5DE, /* [11] m=-10786 b= 20081 */
    0x502AD38E, /* [12] m=-11378 b= 20522 */
};

#endif /* TRIG_PWL_TABLES_H */
